## <b>Import necessary libraries

In [1]:
import pandas as pd
import numpy as np

## Load the dataset

In [2]:
orders = pd.DataFrame([
    [1001, "C01", "Ayan",   "Dhaka",      "Electronics", "2026-01-03", 1850, 2, 3, "Card"],
    [1002, "C02", "Mim",    "Khulna",     "Clothing",    "2026-01-04",  950, 3, 2, "Cash"],
    [1003, "C03", "Rafi",   "Dhaka",      "Books",       "2026-01-05",  620, 2, 4, "Mobile Banking"],
    [1004, "C04", "Nila",   "Rajshahi",   "Groceries",   "2026-01-05", 1320, 6, 1, "Cash"],
    [1005, "C01", "Ayan",   "Dhaka",      "Books",       "2026-01-07",  780, 3, 2, "Card"],
    [1006, "C05", "Sami",   "Chattogram", "Electronics", "2026-01-08", 2450, 1, 5, "Mobile Banking"],
    [1007, "C06", "Toma",   "Khulna",     "Groceries",   "2026-01-09", 1100, 5, 1, "Cash"],
    [1008, "C03", "Rafi",   "Dhaka",      "Clothing",    "2026-01-10", 1450, 4, 3, "Mobile Banking"],
    [1009, "C07", "Jui",    "Rajshahi",   "Books",       "2026-01-11",  540, 2, 2, "Card"],
    [1010, "C08", "Nafis",  "Dhaka",      "Groceries",   "2026-01-12", 1680, 7, 1, "Cash"],
    [1011, "C02", "Mim",    "Khulna",     "Electronics", "2026-01-13", 3200, 2, 4, "Card"],
    [1012, "C09", "Rupa",   "Chattogram", "Clothing",    "2026-01-14", 1250, 3, 3, "Mobile Banking"],
    [1013, "C10", "Hasan",  "Rajshahi",   "Groceries",   "2026-01-15",  980, 4, 1, "Cash"],
    [1014, "C05", "Sami",   "Chattogram", "Books",       "2026-01-16",  860, 4, 2, "Mobile Banking"],
    [1015, "C06", "Toma",   "Khulna",     "Clothing",    "2026-01-17", 1750, 5, 3, "Card"],
    [1016, "C01", "Ayan",   "Dhaka",      "Electronics", "2026-01-18", 2750, 1, 5, "Card"],
    [1017, "C11", "Sadia",  "Dhaka",      "Books",       "2026-01-19",  710, 2, 2, "Mobile Banking"],
    [1018, "C12", "Imran",  "Chattogram", "Groceries",   "2026-01-20", 1540, 6, 1, "Cash"],
    [1019, "C03", "Rafi",   "Dhaka",      "Books",       "2026-01-21",  890, 3, 2, "Card"],
    [1020, "C08", "Nafis",  "Dhaka",      "Electronics", "2026-01-22", 3600, 2, 4, "Mobile Banking"],
], columns=[
    "order_id", "customer_id", "customer_name", "city", "category", "order_date",
    "order_amount", "items", "delivery_days", "payment_method"
])

orders["order_date"] = pd.to_datetime(orders["order_date"])

In [3]:
orders.head()

,order_id,customer_id,customer_name,city,category,order_date,order_amount,items,delivery_days,payment_method
0,1001,C01,Ayan,Dhaka,Electronics,2026-01-03,1850,2,3,Card
1,1002,C02,Mim,Khulna,Clothing,2026-01-04,950,3,2,Cash
2,1003,C03,Rafi,Dhaka,Books,2026-01-05,620,2,4,Mobile Banking
3,1004,C04,Nila,Rajshahi,Groceries,2026-01-05,1320,6,1,Cash
4,1005,C01,Ayan,Dhaka,Books,2026-01-07,780,3,2,Card

In [4]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        20 non-null     int64
 1   customer_id     20 non-null     object
 2   customer_name   20 non-null     object
 3   city            20 non-null     object
 4   category        20 non-null     object
 5   order_date      20 non-null     datetime64[ns]
 6   order_amount    20 non-null     int64
 7   items           20 non-null     int64
 8   delivery_days   20 non-null     int64
 9   payment_method  20 non-null     object
dtypes: datetime64[ns](1), int64(4), object(5)
memory usage: 1.7+ KB

## Find the mean, median, minimum, maximum, and standard deviation of order_amount

In [5]:
print("mean order_amount:", orders['order_amount'].mean())
print("median order_amount:", orders['order_amount'].median())
print("minimum order_amount:", orders['order_amount'].min())
print("maximum order_amount:",orders['order_amount'].max())
print("standard deviation of order_amount",orders['order_amount'].std())

mean order_amount: 1513.5
median order_amount: 1285.0
minimum order_amount: 540
maximum order_amount: 3600
standard deviation of order_amount 871.5036914497415

## Find the earliest and latest order_date

In [6]:
print("earliest order_date", orders["order_date"].min())
print("latest order_date", orders["order_date"].max())

earliest order_date 2026-01-03 00:00:00
latest order_date 2026-01-22 00:00:00

## Create a function pct30() that returns the 30th percentile of a column, then use .agg() to find the 30th percentile of order_amount.

In [7]:
def pct30(column): 
    return column.quantile(0.3)

In [8]:
orders['order_amount'].agg(pct30)

np.float64(932.0)

## Use .agg() to calculate the mean and median of both order_amount and delivery_days

In [9]:
orders[['order_amount', 'delivery_days']].agg([np.mean, np.median])

C:\Users\Fayshal01\AppData\Local\Temp\ipykernel_20816\2918837200.py:1: FutureWarning: The provided callable <function mean at 0x0000019EE0262FC0> is currently using Series.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  orders[['order_amount', 'delivery_days']].agg([np.mean, np.median])
C:\Users\Fayshal01\AppData\Local\Temp\ipykernel_20816\2918837200.py:1: FutureWarning: The provided callable <function median at 0x0000019EE03D49A0> is currently using Series.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  orders[['order_amount', 'delivery_days']].agg([np.mean, np.median])
C:\Users\Fayshal01\AppData\Local\Temp\ipykernel_20816\2918837200.py:1: FutureWarning: The provided callable <function mean at 0x0000019EE0262FC0> is currently using Series.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  orders[['order_amount', 'delivery_days']].agg([np.mean, np.median])
C:\Users\Fayshal01\AppData\Local\Temp\ipykernel_20816\2918837200.py:1: FutureWarning: The provided callable <function median at 0x0000019EE03D49A0> is currently using Series.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  orders[['order_amount', 'delivery_days']].agg([np.mean, np.median])

        order_amount  delivery_days
mean          1513.5           2.55
median        1285.0           2.00

## Sort the data by order_date, then create a new column cumulative_sales showing the cumulative sum of order_amount

In [10]:
orders['order_date'].sort_values()

0    2026-01-03
1    2026-01-04
2    2026-01-05
3    2026-01-05
4    2026-01-07
5    2026-01-08
6    2026-01-09
7    2026-01-10
8    2026-01-11
9    2026-01-12
10   2026-01-13
11   2026-01-14
12   2026-01-15
13   2026-01-16
14   2026-01-17
15   2026-01-18
16   2026-01-19
17   2026-01-20
18   2026-01-21
19   2026-01-22
Name: order_date, dtype: datetime64[ns]

In [11]:
orders['cumulative_sales'] = orders['order_amount'].cumsum()

In [12]:
orders.head()

,order_id,customer_id,customer_name,city,category,order_date,order_amount,items,delivery_days,payment_method,cumulative_sales
0,1001,C01,Ayan,Dhaka,Electronics,2026-01-03,1850,2,3,Card,1850
1,1002,C02,Mim,Khulna,Clothing,2026-01-04,950,3,2,Cash,2800
2,1003,C03,Rafi,Dhaka,Books,2026-01-05,620,2,4,Mobile Banking,3420
3,1004,C04,Nila,Rajshahi,Groceries,2026-01-05,1320,6,1,Cash,4740
4,1005,C01,Ayan,Dhaka,Books,2026-01-07,780,3,2,Card,5520

## Create another column highest_order_so_far using cumulative maximum of order_amount.

In [13]:
orders['highest_order_so_far']= orders['order_amount'].cummax()

In [14]:
orders.head()

,order_id,customer_id,customer_name,city,category,order_date,order_amount,items,delivery_days,payment_method,cumulative_sales,highest_order_so_far
0,1001,C01,Ayan,Dhaka,Electronics,2026-01-03,1850,2,3,Card,1850,1850
1,1002,C02,Mim,Khulna,Clothing,2026-01-04,950,3,2,Cash,2800,1850
2,1003,C03,Rafi,Dhaka,Books,2026-01-05,620,2,4,Mobile Banking,3420,1850
3,1004,C04,Nila,Rajshahi,Groceries,2026-01-05,1320,6,1,Cash,4740,1850
4,1005,C01,Ayan,Dhaka,Books,2026-01-07,780,3,2,Card,5520,1850

## Find the total number of unique customers using drop_duplicates() on customer_id

In [15]:
orders['customer_id'].drop_duplicates()

0     C01
1     C02
2     C03
3     C04
5     C05
6     C06
8     C07
9     C08
11    C09
12    C10
16    C11
17    C12
Name: customer_id, dtype: object

## Find the number of unique customer-category pairs using drop_duplicates() on ["customer_id", "category"].

In [16]:
orders[['customer_id', 'category']].drop_duplicates()

   customer_id     category
0          C01  Electronics
1          C02     Clothing
2          C03        Books
3          C04    Groceries
4          C01        Books
5          C05  Electronics
6          C06    Groceries
7          C03     Clothing
8          C07        Books
9          C08    Groceries
10         C02  Electronics
11         C09     Clothing
12         C10    Groceries
13         C05        Books
14         C06     Clothing
16         C11        Books
17         C12    Groceries
19         C08  Electronics

## Show the count of orders for each category using value_counts()

In [17]:
orders['category'].value_counts()

category
Books          6
Electronics    5
Groceries      5
Clothing       4
Name: count, dtype: int64

## Show the proportion of orders for each category

In [18]:
orders['category'].value_counts(normalize=True)

category
Books          0.30
Electronics    0.25
Groceries      0.25
Clothing       0.20
Name: proportion, dtype: float64

## Find the average order_amount for each city

In [19]:
orders.groupby('city')['order_amount'].mean()

city
Chattogram    1525.000000
Dhaka         1592.222222
Khulna        1750.000000
Rajshahi       946.666667
Name: order_amount, dtype: float64

## For each category, calculate the minimum, maximum, and sum of order_amount

In [20]:
orders.groupby('category')['order_amount'].agg([min, max, sum])

C:\Users\Fayshal01\AppData\Local\Temp\ipykernel_20816\305172174.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  orders.groupby('category')['order_amount'].agg([min, max, sum])
C:\Users\Fayshal01\AppData\Local\Temp\ipykernel_20816\305172174.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  orders.groupby('category')['order_amount'].agg([min, max, sum])
C:\Users\Fayshal01\AppData\Local\Temp\ipykernel_20816\305172174.py:1: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  orders.groupby('category')['order_amount'].agg([min, max, sum])

              min   max    sum
category
Books         540   890   4400
Clothing      950  1750   5400
Electronics  1850  3600  13850
Groceries     980  1680   6620

## Group by both city and category, then find the average order_amount.

In [21]:
orders.groupby(["city", 'category'])['order_amount'].mean()

city        category
Chattogram  Books           860.000000
            Clothing       1250.000000
            Electronics    2450.000000
            Groceries      1540.000000
Dhaka       Books           750.000000
            Clothing       1450.000000
            Electronics    2733.333333
            Groceries      1680.000000
Khulna      Clothing       1350.000000
            Electronics    3200.000000
            Groceries      1100.000000
Rajshahi    Books           540.000000
            Groceries      1150.000000
Name: order_amount, dtype: float64

## For each payment_method, calculate:
* average delivery_days
* total order_amount

In [22]:
orders.groupby('payment_method')[['delivery_days', 'order_amount']].agg([np.mean, sum])

C:\Users\Fayshal01\AppData\Local\Temp\ipykernel_20816\1547292111.py:1: FutureWarning: The provided callable <function mean at 0x0000019EE0262FC0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  orders.groupby('payment_method')[['delivery_days', 'order_amount']].agg([np.mean, sum])
C:\Users\Fayshal01\AppData\Local\Temp\ipykernel_20816\1547292111.py:1: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  orders.groupby('payment_method')[['delivery_days', 'order_amount']].agg([np.mean, sum])
C:\Users\Fayshal01\AppData\Local\Temp\ipykernel_20816\1547292111.py:1: FutureWarning: The provided callable <function mean at 0x0000019EE0262FC0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  orders.groupby('payment_method')[['delivery_days', 'order_amount']].agg([np.mean, sum])

               delivery_days     order_amount
                        mean sum         mean    sum
payment_method
Card                3.000000  21  1680.000000  11760
Cash                1.166667   7  1261.666667   7570
Mobile Banking      3.285714  23  1562.857143  10940

## Create a pivot table showing the average order_amount for each city

In [24]:
orders.pivot_table(values='order_amount', index='city', aggfunc="mean")

            order_amount
city
Chattogram   1525.000000
Dhaka        1592.222222
Khulna       1750.000000
Rajshahi      946.666667

## Create a pivot table where:
* rows = city
* columns = category
* values = average order_amount

In [25]:
orders.pivot_table(values='order_amount', index='city', aggfunc="mean", columns='category')

category    Books  Clothing  Electronics  Groceries
city
Chattogram  860.0    1250.0  2450.000000     1540.0
Dhaka       750.0    1450.0  2733.333333     1680.0
Khulna        NaN    1350.0  3200.000000     1100.0
Rajshahi    540.0       NaN          NaN     1150.0

## Repeat Question 17 but replace missing values with 0

In [26]:
orders.pivot_table(values='order_amount', index='city', aggfunc="mean", columns='category', fill_value= 0)

category    Books  Clothing  Electronics  Groceries
city
Chattogram  860.0    1250.0  2450.000000     1540.0
Dhaka       750.0    1450.0  2733.333333     1680.0
Khulna        0.0    1350.0  3200.000000     1100.0
Rajshahi    540.0       0.0     0.000000     1150.0

## Add margins=True to the pivot table to show overall averages.

In [27]:
orders.pivot_table(values='order_amount', index='city', aggfunc="mean", columns='category', margins=True)

category         Books  Clothing  Electronics  Groceries          All
city
Chattogram  860.000000    1250.0  2450.000000     1540.0  1525.000000
Dhaka       750.000000    1450.0  2733.333333     1680.0  1592.222222
Khulna             NaN    1350.0  3200.000000     1100.0  1750.000000
Rajshahi    540.000000       NaN          NaN     1150.0   946.666667
All         733.333333    1350.0  2770.000000     1324.0  1513.500000

## Find all customers who placed more than one order.

In [33]:
orders['customer_id'].value_counts()

customer_id
C01    3
C03    3
C02    2
C05    2
C08    2
C06    2
C04    1
C07    1
C09    1
C10    1
C11    1
C12    1
Name: count, dtype: int64

## Find the customer who spent the highest total amount.

In [38]:
orders[orders['order_amount'] == orders['order_amount'].max()]

,order_id,customer_id,customer_name,city,category,order_date,order_amount,items,delivery_days,payment_method,cumulative_sales,highest_order_so_far
19,1020,C08,Nafis,Dhaka,Electronics,2026-01-22,3600,2,4,Mobile Banking,30270,3600